sudo: required
language: cpp

matrix:
  fast_finish: true
  include:
    - os: linux      
      services:
        - docker
      before_install:
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get -y install docker-ce
      script:
        - mkdir -p ${TRAVIS_BUILD_DIR}/install
        - docker-compose run plugin-build
        - docker-compose build orthanc-plugins
        - docker tag mschmieder/orthanc-plugins:latest mschmieder/orthanc-plugins:${TRAVIS_BRANCH} 
        - |
          if [[ "${TRAVIS_BRANCH}" == "master" ]]; then
            docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
            docker push mschmieder/orthanc-plugins:${TRAVIS_BRANCH}
          fi
        - |
          if [ -n "${TRAVIS_TAG}" ]; then  
            docker push mschmieder/orthanc-plugins:latest 
          fi
      after_success:
        - cd ${TRAVIS_BUILD_DIR}/install && tar cfzv ${TRAVIS_BUILD_DIR}/plugin-linux.${TRAVIS_BRANCH}.tar.gz *
    # - os: osx
    #   osx_image: xcode9.4   
    #   before_install:
    #     - brew update
    #     - brew install wget boost cmake cpprestsdk cryptopp gettext glog jsoncpp libxml2
    #   env: 
    #     - USE_VCPKG=1
    #     - ORTHANC_VERSION=1.4.0
    #   script:
    #     - bash bootstrap.sh
    #     - bash build.sh
    #   after_success:
    #     - cd ${TRAVIS_BUILD_DIR}/install && tar cfzv ${TRAVIS_BUILD_DIR}/orthanc-azure-blob-storage-plugin-osx-${TRAVIS_BRANCH}.tar.gz *
deploy:
  - provider: releases
    api_key:
      secure: kr9G+V2zMy/8QKGtlNPl+jytCc6Z0eq8HEmrsawbfnqWjudR3uw3YOPKS3XEvNlSxeaGj9VNdrYLEs/AuD1EB/F/pNmUn1/ZpUK/35L7Ybup7mfnTyAYvkODB0JkyCxmhGqCcGIptSOqR7Zmi4sWKMHC8uTzwsRYvJucA0cKzLMDmqMfnHpvGHCDgwztf3hbxVWF+MPPHkTDbDRBzoGy6kwbPKtR9IDp5CcJykmyn7KRqBqh7XfFS/FXUfmNq8a/j9684V2Iv8D6bIOvT30n7k9mcSwpdKJEmrZ1ZjyUfZFcSiGJ7WykQfTIDzAIhgpXSt/APOATfvxAxIvRQyejtAoqu4mIxW7kTgUZPGgyi5EQUKC4//Ft2GH/Fx5Mt02rsRyFJ48nGWfH4GJVZCzjMftuMshvg9OdRnlInh3uXFyIMR7oYwC5ztZx6OYpURQXQ33Cz58Bl2/x4EH+nfYCzbkVAuXzMzJfc4UHWK55UPGImgi41KNA7oJ13+hgBVrStQ1RCV7I/Mp7SKrfk2gd1TimdxRNMawAG8S+IZ5IZ8QpFy+Jy9i5TPDx8MXzk0hplMyIlyB7e/mZUW9Fw/ndJ2Hc6flvJ1CQWSS/LuGTNCetjVJZ3CoCPQh52Yfb8tMpha92QOtwby+oJ1MQmBEWllGeRw61Q4DJ9EkBXiMwVYg=
    file_glob: true
    file: 
      - ${TRAVIS_BUILD_DIR}/plugin-*.tar.gz
    skip_cleanup: true
    name: "Release-Version ${TRAVIS_TAG}"
    body: "Released version ${TRAVIS_TAG} of Orthanc Azure Blob Storage Plugin"
    on:
      tags: true
  - provider: releases
    api_key:
        secure: kr9G+V2zMy/8QKGtlNPl+jytCc6Z0eq8HEmrsawbfnqWjudR3uw3YOPKS3XEvNlSxeaGj9VNdrYLEs/AuD1EB/F/pNmUn1/ZpUK/35L7Ybup7mfnTyAYvkODB0JkyCxmhGqCcGIptSOqR7Zmi4sWKMHC8uTzwsRYvJucA0cKzLMDmqMfnHpvGHCDgwztf3hbxVWF+MPPHkTDbDRBzoGy6kwbPKtR9IDp5CcJykmyn7KRqBqh7XfFS/FXUfmNq8a/j9684V2Iv8D6bIOvT30n7k9mcSwpdKJEmrZ1ZjyUfZFcSiGJ7WykQfTIDzAIhgpXSt/APOATfvxAxIvRQyejtAoqu4mIxW7kTgUZPGgyi5EQUKC4//Ft2GH/Fx5Mt02rsRyFJ48nGWfH4GJVZCzjMftuMshvg9OdRnlInh3uXFyIMR7oYwC5ztZx6OYpURQXQ33Cz58Bl2/x4EH+nfYCzbkVAuXzMzJfc4UHWK55UPGImgi41KNA7oJ13+hgBVrStQ1RCV7I/Mp7SKrfk2gd1TimdxRNMawAG8S+IZ5IZ8QpFy+Jy9i5TPDx8MXzk0hplMyIlyB7e/mZUW9Fw/ndJ2Hc6flvJ1CQWSS/LuGTNCetjVJZ3CoCPQh52Yfb8tMpha92QOtwby+oJ1MQmBEWllGeRw61Q4DJ9EkBXiMwVYg=
    file_glob: true
    file: 
      - ${TRAVIS_BUILD_DIR}/plugin-*.tar.gz
    skip_cleanup: true
    preprelease: true
    name: "Pre-Release Version ${TRAVIS_TAG}"
    body: "Pre-Released version ${TRAVIS_TAG} of Orthanc Azure Blob Storage Plugin"
    on:
      branch: master
      

