version: '3'

services:
  monolithic-build:
    image: orthanc-azure-blob-storage-plugin-sdk
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ORTHANC_VERSION: 1.3.1 
    volumes:
      - .:/src
    working_dir: /src
    environment:
      ORTHANC_ROOT: /bootstrap/Orthanc-1.3.1
      BUILD_DIR: /src/build
      INSTALL_DIR: /src/install
      VCPKG_DIR: /bootstrap/vcpkg
    command: /bin/bash build.sh
  github-build:
    image: mschmieder/orthanc-azure-blob-storage-plugin-sdk
    volumes:
      - .:/src
    working_dir: /src
    environment:
      ORTHANC_ROOT: /bootstrap/Orthanc-1.3.1
      BUILD_DIR: /src/build
      INSTALL_DIR: /src/install
      VCPKG_DIR: /bootstrap/vcpkg
    command: /bin/bash build.sh