version: '3'

services:
  build-plugin:
    image: orthanc-azure-blob-storage-plugin-sdk
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ORTHANC_VERSION: 1.4.0 
    volumes:
      - .:/src
    working_dir: /src
    environment:
      CMAKE_BINARY: /opt/cmake/bin/cmake
      BUILD_DIR: /src/build
      INSTALL_DIR: /src/install
      CPPRESTSDK_ROOT: /cpprestsdk-dev
    command: /bin/bash -c "/bin/bash bootstrap.sh && /bin/bash build.sh"