version: '3'

services:
  sdk:
    image: mschmieder/orthanc-azure-blob-storage-plugin-sdk:ubuntu-18.04
    build:
      context: .
      dockerfile: docker/Dockerfile.sdk
      args:
        ORTHANC_VERSION: 1.4.1

  orthanc:
    image: mschmieder/orthanc:1.4.1-ubuntu-18.04
    build:
      context: .
      dockerfile: docker/Dockerfile.orthanc
      args:
        ORTHANC_VERION: 1.4.1
    ports:
      - "8042:8042"
      - "4242:4242"

  orthanc-plugins:
    image: mschmieder/orthanc-plugins
    build:
      context: .
      dockerfile: docker/Dockerfile.orthanc-plugins
      args:
        ORTHANC_VERSION: 1.4.1
    ports:
      - "8042:8042"
      - "4242:4242"
    volumes:
      - ./plugin-config.json:/etc/orthanc/plugin-config.json