version: '3'

services:
  sdk-build:
    image: mschmieder/orthanc-azure-blob-storage-plugin-sdk:ubuntu-16.04
    build:
      context: .
      dockerfile: docker/Dockerfile.sdk
      args:
        ORTHANC_VERSION: 1.4.1

  plugin-build:
    image: mschmieder/orthanc-azure-blob-storage-plugin-sdk:ubuntu-16.04
    volumes:
      - .:/src
    environment:
      BUILD_DIR: /src/build
      INSTALL_DIR: /src/install
    working_dir: /src
    command: /bin/bash -c "/bin/bash build.sh"

  orthanc:
    image: mschmieder/orthanc
    build:
      context: .
      dockerfile: docker/Dockerfile.orthanc
      args:
        ORTHANC_VERIONS: 1.4.1
    ports:
      - "8042:8042"
      - "4242:4242"
  
  orthanc-plugins:
    image: mschmieder/orthanc-plugins
    build:
      context: .
      dockerfile: docker/Dockerfile.orthanc-plugins
    ports:
      - "8042:8042"
      - "4242:4242"
    volumes:
      - ./plugin-config.json:/etc/orthanc/plugin-config.json