version: '3'

services:
  build-sdk:
    image: mschmieder/orthanc-azure-blob-storage-plugin-sdk:ubuntu-18.04
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ORTHANC_VERSION: 1.4.0
        USE_VCPKG: 1
  
  build-plugin:
    image: mschmieder/orthanc-azure-blob-storage-plugin-sdk:ubuntu-18.04
    volumes:
      - .:/src
    environment:
      ORTHANC_ROOT: /Orthanc-1.4.0
      BUILD_DIR: /src/build
      INSTALL_DIR: /src/install
      VCPKG_ROOT: /vcpkg
      USE_VCPKG: "1"
    working_dir: /src
    command: /bin/bash -c "/bin/bash build.sh"