FROM ubuntu:18.04
MAINTAINER Matthias Schmieder <schmieder.matthias@gmail.com>

RUN apt-get update -qq && \
    apt-get install -y wget software-properties-common cmake git gcc g++ curl unzip tar

COPY . /src
WORKDIR /src

RUN ./build.sh