FROM ubuntu:18.04 as builder

RUN apt-get update -qq && apt-get install -y \
       wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# download plugin from github

FROM jodogne/orthanc:1.4.1